# 用来指定环境,  公告配置也可以写这里
server:
  port: 808
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/caidingnu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: my
      max-lifetime: 1800000
      connection-test-query:  SELECT 1
      connection-timeout: 8000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.baomidou.ant.entity