server:
  port: 80 #为了以后访问项目不用写端口号
  context-path: / #为了以后访问项目不用写项目名
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.28.171.44:3306/urp?useUnicode=true&characterEncoding=utf-8  #解决中文乱码的问题
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #数据库同步代码
    show-sql: true      #dao操作时，显示sql语句

  thymeleaf:
    mode: LEGACYHTML5

  redis:
    host: 129.28.171.44
    port: 6379
    password:
    timeout: 0
    #    database: 0  #默认库
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8   # 连接池中的最大空闲连接
      min-idle: 0   # 连接池中的最小空闲连接


