server:
  port: 808
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3806/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
