server:
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
  datasource:
    url: jdbc:mysql://127.0.0.1:3806/quart?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    password: Admin@123
    username: root
  http:
    encoding:
      charset: utf-8
      force: true
logging:
  level:
    org.springframework: debug

#      ####  以下是内存用户时候使用  ###############
merryyou:
  security:
    oauth2:
      storeType: redis #或者jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: merryyou
      clients[1]:
        clientId: merryyou1
        clientSecret: merryyou1
