server:
  port: 89


spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: manual   # 手动确认消息