#server:
#  port: 8763
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
#    lease-renewal-interval-in-seconds: 10
#    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
#    lease-expiration-duration-in-seconds: 15
#
#
##客户端默认是30s发送一次心跳，90s服务端没有收到心跳就把服务剔除
#
#
#spring:
#  application:
#    name: service-movie
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sewer?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root


#server:
#  port: 8765
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
#    lease-renewal-interval-in-seconds: 10
#    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
#    lease-expiration-duration-in-seconds: 15
#
#
##客户端默认是30s发送一次心跳，90s服务端没有收到心跳就把服务剔除
#
#
#spring:
#  application:
#    name: service-movie
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sewer?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root


#客户端默认是30s发送一次心跳，90s服务端没有收到心跳就把服务剔除
#spring:
#  #-----------------本地-----------------
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      #      uri: http://localhost:8888/   #直接用ip调用配置中心服务端，用于没有将配置中心服务端注册到注册中心的时候
#      name: movie-application
#      profile: dev
#dev开发环境配置文件
#test测试环境
#pro正式环境

#------------  GItHub---------------
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://localhost:8888/
#          search-paths: respo
#          username:
#          password:
#      label: master
#      profile: dev