server:
  port: 80

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/auth?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tese.boot.entity
  #redis配置



