server:
  port: 80
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/caidingnu?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        pool-name: master
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cdntwo?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        pool-name: master
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000


logging:
  config: classpath:config/logback.xml

#----------------  整合动态数据源之后 以下配置被configuration中的SqlSessionFactoryBean覆盖了，也就是无效了
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity

