server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
    #  instance-id: ${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}





spring:
  application:
    name: service-movie
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sewer?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
