server:
  port: 88


spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /test
    template:
      retry:
        #enabled：开启失败重试
        enabled: true
        #第一次重试的间隔时长
        initial-interval: 10000ms
        #最长重试间隔，超过这个间隔将不再重试
        max-interval: 300000ms
        #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
        multiplier: 2
      #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
      #确认消息已发送到队列(Queue)
    publisher-returns: true