server:
  port: 10000
spring:
  application:
    name: eureka
#  security:
#    user:
#      name: user
#      password: user

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/