server:
  port: 80

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/chenyun01
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 9
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000  #redis 连接超时时间ms
    database: 0
    # 数据的默认保存有效时间
    validDay: 1
  cache:
    type: redis
    redis:
      time-to-live: 20000 #缓存失效时间ms
      cache-null-values: false #是否缓存空值


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.oceam.entity
  #redis配置



