server:
  port: 8888


spring:
  application:
    name: config-server
  #   本地
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #          配置文件在D盘的config文件夹下
          search-locations: file:///D:/config
#    Github---
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/forezp/SpringcloudConfig/
#           profile: dev
#          search-paths: respo
#          username:
#          password:
#      label: master

#      本地
