spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/caidingnu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  redis:
    database: 0
    host: 129.28.171.44
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5   # 连接池中的最小空闲连接

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
server:
  port: 81
