server:
  port: 8099

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/caidingnu
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml

#####################################################################################################
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#####################################################################################################
