#server:
#  port: 8769
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
#    #  instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
#
#spring:
#  application:
#    name: service-zuul
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sewer?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#
#
#feign:
#  hystrix:
#    enabled: true   #打开Feign自带的断路器
#
#zuul:
#  routes:
#    api-movie:
#      path: /api-movie:/**
#      serviceId: service-movie
#    api-user:
#      path: /api-user/**
#      serviceId: service-user

#客户端默认是30s发送一次心跳，90s服务端没有收到心跳就把服务剔除
spring:
  #-----------------本地-----------------
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      #      uri: http://localhost:8888/   #直接用ip调用配置中心服务端，用于没有将配置中心服务端注册到注册中心的时候
      name: zuul-application-pro
      profile: pro

#dev开发环境配置文件
#test测试环境
#pro正式环境

#------------  GItHub---------------
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://localhost:8888/
#          search-paths: respo
#          username:
#          password:
#      label: master
#      profile: dev