server:
  port: 80

# mysql 属性配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ybq?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志


