server:
  port: 86
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdn?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      pool-name: master
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cdn2?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        pool-name: master
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/stu?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        pool-name: master
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1765000
############  datasourceName 多数据源时必须，不需要多数据源的时候请注释或者删除
datasourceName: slave1,slave2


logging:
  config: classpath:config/logback.xml


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ht.ldinfo.servicemanagement.entity
  configuration:
    map-underscore-to-camel-case: true
